feat: создание каркаса по ТЗ-9
akrecev/java-filmorate pull request #1
Opened 2022-11-04 09:55 UTC by akrecev

#1 создание каркаса filmorate

2022-11-04 12:15 UTC, FanaticFiz requested changes
Финальный комментарий на Я.Практикуме

2022-11-04 12:15 UTC, FanaticFiz commented on pom.xml
> +		<java.version>11</java.version>
Ну что же, начнем с "многоуважаемого" `pom` файла ))

Для начала немного причесать: очень не хватает отделения друг от друга (пустыми строками) глобальных частей таких как `parent`, `properties`, `dependencies`

Ну и как минимум не хватает указания кодировки в `properties<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>`

2022-11-04 12:15 UTC, FanaticFiz commented on pom.xml
> +	<version>0.0.1-SNAPSHOT</version>
Советую прочитать про семантическое версионирование, ну а после, не стесняйся - смело проставь версию!

2022-11-04 12:15 UTC, FanaticFiz commented on src/main/resources/application.properties
> +logging.level.ru.yandex.practicum.filmorate=debug
Я буду топить за то чтобы вы сразу привыкали к написанию файла свойств для приложения в формате `yaml -> application.yml`

Соответственно - попрошу тебя этому следовать.
Как мини задание: разберись как задать порт для сервиса отличный от дефолтного, и как задать чтобы порт был случайным.
(Менять порт на другой не нужно, для тестов нужен именно 8080)

2022-11-04 12:15 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +package ru.yandex.practicum.filmorate.model;
Название пакетов не однородно, где то во множественном числе, где то в единственном.
Приведи к единому стилю.

2022-11-04 12:15 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/exceptions/ValidationException.java
> +public class ValidationException extends RuntimeException {
Да, этот ексепшн мы кидаем когда находим ошибку при валидации полей.
Но это у нас веб сервис и это происходит во время запросов к нашему сервису... и клиента мы отсылаем с формулировкой "плохой запрос": `BadRequest` -> `BadRequestException`

2022-11-04 12:15 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +    private final static LocalDate CINEMA_BIRTHDAY = LocalDate.of(1895, Month.DECEMBER, 28);
Существует порядок объявления полей класса. 
По нему статики должны быть первыми...

2022-11-04 12:15 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +            throw new ValidationException("Фильма с таким id не существует");
А в этом случае нам нужен другой ексепшн. 
Отдельный, как раз на такой случай: `ConflictException`

2022-11-04 12:15 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +        log.debug("Фильм " + film.getName() + " id: " + film.getId() + " обновлен");
Ты некорректно пользуешься логером... 
у него есть возможность подстановки переменных через `{}` и этим надо пользоваться!

2022-11-05 08:54 UTC, akrecev commented on pom.xml
> +		<java.version>11</java.version>
Хорошо, спасибо за подсказку. Не обратил внимание на читаемость структуры `pom` файла

2022-11-05 08:55 UTC, akrecev commented on src/main/resources/application.properties
> +logging.level.ru.yandex.practicum.filmorate=debug
Да, `.yml` лучше

2022-11-05 08:56 UTC, akrecev commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +package ru.yandex.practicum.filmorate.model;
Поправил

2022-11-05 08:57 UTC, akrecev commented on src/main/java/ru/yandex/practicum/filmorate/exceptions/ValidationException.java
> +public class ValidationException extends RuntimeException {
Исправил

2022-11-05 08:57 UTC, akrecev commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +    private final static LocalDate CINEMA_BIRTHDAY = LocalDate.of(1895, Month.DECEMBER, 28);
Да, не обратил внимание

2022-11-05 08:58 UTC, akrecev commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +            throw new ValidationException("Фильма с таким id не существует");
Разделил исключения

2022-11-05 08:59 UTC, akrecev commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +        log.debug("Фильм " + film.getName() + " id: " + film.getId() + " обновлен");
Показалось что структура с `+ ... +` более читаема. Исправил

2022-11-05 09:09 UTC, akrecev commented
Внес изменения замечаниям

2022-11-05 09:18 UTC, akrecev commented on src/main/resources/application.properties
> +logging.level.ru.yandex.practicum.filmorate=debug
Для задания случайного порта нужно указать 0

2022-11-05 09:19 UTC, akrecev commented on pom.xml
> +	<version>0.0.1-SNAPSHOT</version>
проставил версию 0.1.1 - посчитал свои изменения патчем

2022-11-05 12:06 UTC, FanaticFiz approved these changes

2022-11-14 10:20 UTC, merged