Develop
akrecev/java-filmorate pull request #15
Opened 2022-12-23 19:40 UTC by akrecev

Денис привет! Отправляю наш совместный проект на рассмотрение.

2022-12-24 16:20 UTC, FanaticFiz requested changes
Финальный комментарий на Я.Практикуме

2022-12-24 16:20 UTC, FanaticFiz commented on pom.xml
Привет, команда!
Начну с организационного вопроса.
Только один человек представился в гите правильно: `Ruslan Buldakov`
Руслан красавчик! Остальным не стесняться - пусть все знают кто написал код! ))

![image](https://user-images.githubusercontent.com/3994663/209442961-a0d785f8-f81b-4967-ab78-45e7a69d44fa.png)

2022-12-24 16:20 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/controller/ReviewController.java
> +        return reviews;
Всегда предпочитайте иметь один `return` на метод, и стремитесь к этому.

```
    private List<Review> getFilmAllReviews(@RequestParam(defaultValue = "0") long filmId,
                                           @RequestParam(defaultValue = "10") int count) {
        List<Review> reviews;
        if (filmId == 0) {
            reviews = reviewService.getAllReviews(count);
            log.debug("Get {} reviews", reviews.size());
        } else {
            reviews = reviewService.getFilmAllReviews(filmId, count);
            log.debug("Get {} reviews for film id:{}", reviews.size(), filmId);
        }

        return reviews;
    }
```

2022-12-24 16:20 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +import lombok.Data;
Не подчищены импорты...

2022-12-24 16:20 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +                       MpaService mpaService, GenreStorage genreStorage, DirectorStorage directorStorage, UserActionsStorage userActionsStorage) {
Не поместилось в строку - переносите!
Вот прям вот так:

```
    @Autowired
    public FilmService(FilmStorage filmStorage,
                       UserService userService,
                       LikesStorage likesStorage,
                       MpaService mpaService,
                       GenreStorage genreStorage,
                       DirectorStorage directorStorage,
                       UserActionsStorage userActionsStorage) {
        this.filmStorage = filmStorage;
        this.userService = userService;
        this.likesStorage = likesStorage;
        this.mpaService = mpaService;
        this.genreStorage = genreStorage;
        this.directorStorage = directorStorage;
        this.userActionsStorage = userActionsStorage;
    }
```

Пусть вас это пугает!! 
Да да - я не опечатался именно ПУГАЕТ... большое кол-во импортов в класс должно вас напрячь, вы должны задуматься а не дофига ли их тут, может этот класс слишком много делает?

Сейчас, переделывать не нужно, ну кроме того что выстроить их как я показал...
Но в целом не забывайте об этом!

2022-12-24 16:20 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/storage/db/DirectorDbStorage.java
> +    static Director directorMapper(ResultSet rs, int rowNum) throws SQLException {
Отсутствует модификатор доступа!
И напомню что приватные методы располагаются в классе после публичных...

2022-12-24 16:20 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/storage/db/DirectorDbStorage.java
> +        return find(id).get();
Нельзя брать `get()` у `Optional` без проверки...
Что делать?

Отказаться от find? Зачем мы отсылаем запрос еще раз если вот она сущность директора рядом и с проставленным `id` уже...
Ну или второй вариант... забирать через orElseThrow но из dao могут быть брошены только SQL исключения, которые мы в этой работе не используем...
Третий вариант: в хранилище метод save не возвращает ничего при сохранении, он void. А в сервисе делать find из хранилища.

2022-12-24 16:20 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/storage/db/DirectorDbStorage.java
> +@Component
Используйте спец аннотацию @Repository
И задание для вас: объясните мне чем отличаются аннотации @Repository/Component/Service ?? )))

2022-12-24 18:02 UTC, akrecev commented on src/main/java/ru/yandex/practicum/filmorate/controller/ReviewController.java
> +        return reviews;
Поправил, спасибо за подсказку!

2022-12-24 18:38 UTC, RuslanBoo commented on src/main/java/ru/yandex/practicum/filmorate/storage/db/DirectorDbStorage.java
> +@Component
@Component - аннотация бина spring, @Service - подвид компонента, который показывает что данный бин отвечает за бизнес логику, с точки зрения функционала идентичен компоненту. @Repository тоже наследник от компонента: во первых обозначает что бин работает с бд или выступает в качестве хранилища, а во вторых транслирует исключения (нет необходимости добавлять try catch в работе с БД, он пробросит их дальше с  классом DataAccessException)

2022-12-24 19:33 UTC, Gil4rt commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +import lombok.Data;
Почистил

2022-12-24 19:52 UTC, RuslanBoo commented on src/main/java/ru/yandex/practicum/filmorate/storage/db/DirectorDbStorage.java
> +@Component
аннотация добавил

2022-12-24 19:58 UTC, RuslanBoo commented on src/main/java/ru/yandex/practicum/filmorate/storage/db/DirectorDbStorage.java
> +        return find(id).get();
Переделал метод на void. Перенес метод find() в сервис. На мой взгляд такая реализация позволяет проконтролировать что данные не просто были отправлены на update, но и сам факт что запись в БД изменена и соответсвует ожидаемой

2022-12-24 19:58 UTC, RuslanBoo commented on src/main/java/ru/yandex/practicum/filmorate/storage/db/DirectorDbStorage.java
> +    static Director directorMapper(ResultSet rs, int rowNum) throws SQLException {
Добавил модификатор доступа, перенес метод после public'ов

2022-12-24 20:05 UTC, Gil4rt commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +                       MpaService mpaService, GenreStorage genreStorage, DirectorStorage directorStorage, UserActionsStorage userActionsStorage) {
Поправил

2022-12-24 21:16 UTC, akrecev commented on pom.xml
Обновили имена в гитконфиге.

2022-12-25 12:20 UTC, FanaticFiz approved these changes

2022-12-25 12:22 UTC, FanaticFiz approved these changes

2022-12-25 12:59 UTC, Gil4rt approved these changes

2022-12-25 13:02 UTC, merged