feat: добавление функционала по ТЗ-10
akrecev/java-filmorate pull request #2
Opened 2022-11-16 15:39 UTC by akrecev

2022-11-16 19:18 UTC, FanaticFiz requested changes
Финальный комментарий на Я.Практикуме

2022-11-16 19:18 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/model/StorageData.java
> +    Long id;
id скорее тоже будет NotNull

2022-11-16 19:18 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        if (userId <= 0) {
Но нам мало проверить что id пользователя не меньше 0.
Надо же убедиться что пользователь с таким id существует...

2022-11-16 19:18 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        validateById(id);
Если ты в методе кидаешь ексепш, то и назови метод соответствующе... throw по какой причине?

2022-11-16 19:18 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +            user.setName(user.getLogin());
Присвоение имени по какой то логике это уже не валидация, а бизнес логика нашего приложения.
Она не должна быть тут...

2022-11-16 19:18 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/storage/AbstractDataStorage.java
> +            throw new ConflictException("duplicate id");
Старайся давать больше информации, у тебя же есть конкретный id

2022-11-16 21:51 UTC, akrecev commented on src/main/java/ru/yandex/practicum/filmorate/model/StorageData.java
> +    Long id;
Да, сначала повесил аннотацию `@NotNull` , но вылетели тесты постмана. При создании сущности данные с клиента прилетают без id. Он присваивается в слое storage. А валидация по `@NotNull` происходит на этапе получения данных через запрос. Поэтому `@NotNull` все ломает. Я проверяю юзеров и фильмы уже в своей логике на валидность id в том числе.

2022-11-16 21:52 UTC, akrecev commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        if (userId <= 0) {
Принял. Выполнил проверку на валидность пользователя.

2022-11-16 21:53 UTC, akrecev commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        validateById(id);
Переработал код. Исключил выброс предупреждения из метода. Он там дублировался.

2022-11-16 21:54 UTC, akrecev commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +            user.setName(user.getLogin());
Вынес присвоение имени на этап создания и обновления пользователя.

2022-11-16 21:55 UTC, akrecev commented on src/main/java/ru/yandex/practicum/filmorate/storage/AbstractDataStorage.java
> +            throw new ConflictException("duplicate id");
Добавил значение id сообщение.

2022-11-16 21:57 UTC, akrecev commented
Денис привет! Поправил код по твоим комментариям.

2022-11-17 17:55 UTC, FanaticFiz approved these changes

2022-11-17 20:48 UTC, merged