Add database
akrecev/java-filmorate pull request #4
Opened 2022-12-12 12:54 UTC by akrecev

Привет! Выкладываю обновление filmorate согласно ТЗ-11. Добавлена база данных H2 для хранения данных.

2022-12-12 19:03 UTC, FanaticFiz requested changes
Финальный комментарий на Я.Практикуме

2022-12-12 19:03 UTC, FanaticFiz commented on pom.xml
>      <artifactId>filmorate</artifactId>
Бинарные файл, тем более БД не нужно пушить в исходный код, в гит!

Добавь их в исключение!

2022-12-12 19:03 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        return filmService.save(film);
Зачем ты переименовал название метода?
По отношению к сервису ничего не меняется, как создавали фильм так и создаём!

2022-12-12 19:03 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    private LinkedHashSet<Genre> genres = new LinkedHashSet<>();
В качестве типа нужно указывать интерфейс!

2022-12-12 19:03 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    public FilmService(FilmStorage filmStorage, UserService userService, LikesStorage likesStorage, MpaStorage mpaStorage, GenreStorage genreStorage) {
Строка не помещается в 120 символов.
Нужно делать перенос.

2022-12-12 19:03 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmStorage.java
> +    Film get(long id);
Давай get делать с Optional.

И давай применять в хранилищах глагол find, а в сервисах get

2022-12-12 19:03 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/storage/db/FilmDbStorage.java
> +    static Film filmMapper(ResultSet rs, int rowNum) throws SQLException {
У этого метода не хватает модификатора доступа... а когда он получит свой private то должен будет опуститься ниже публичных методов, не забывай!

2022-12-12 19:03 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/storage/db/FilmDbStorage.java
> +            throw new DataNotFoundException("id=" + id);
Это работа сервиса! 
Из хранилища не должны вылетать такие ексепшены!

И вот посмотри на сервис, он у тебя ничего не делает, просто транслирует действие сюда, а такого быть не должно.

Ты перетащил всё в хранилище...

2022-12-12 19:03 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/storage/db/GenreDBStorage.java
> +    public Genre get(int id) {
Ну ты понимаешь... во всех сервисах я жду от тебя Optional при одиночном get и не забираем работу у сервисов, хранилище просто отдаёт что нашло иди пусто если не нашлось ничего...

2022-12-13 08:38 UTC, akrecev commented on pom.xml
>      <artifactId>filmorate</artifactId>
Привет Денис! Переработал .gitignore

2022-12-13 09:07 UTC, akrecev commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        return filmService.save(film);
Поправил, на вебинарах увидел что метод называют save, показалось логичным переименовать. Но действительно в сервисе лучше оставить create

2022-12-13 09:22 UTC, akrecev commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    private LinkedHashSet<Genre> genres = new LinkedHashSet<>();
При указании интерфейса теряется свойство LinkedHashSet сохранять нужную последовательность жанров в фильме и падает тест в постмане. Долго с этим парился, может что-то сделал неправильно, но при таком вызове списка в методе saveGenres() в классе FilmDbStorage сохраняется переданная извне последовательность жанров, а с Set нет. Видимо когда список genres проходит через геттер, он становится не связанным списком.

2022-12-13 09:54 UTC, akrecev commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    public FilmService(FilmStorage filmStorage, UserService userService, LikesStorage likesStorage, MpaStorage mpaStorage, GenreStorage genreStorage) {
Не увидел, автоматом конструктор поправлял.

2022-12-13 10:00 UTC, akrecev commented on src/main/java/ru/yandex/practicum/filmorate/storage/db/FilmDbStorage.java
> +    static Film filmMapper(ResultSet rs, int rowNum) throws SQLException {
Исправил

2022-12-13 10:08 UTC, akrecev commented on src/main/java/ru/yandex/practicum/filmorate/storage/db/FilmDbStorage.java
> +    static Film filmMapper(ResultSet rs, int rowNum) throws SQLException {
Тут я не могу его сделать приватным, у меня хранилища используют соседние мапперы. Фильмы с лайками, юзеры с друзьями.

2022-12-13 15:24 UTC, akrecev commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmStorage.java
> +    Film get(long id);
Принял. Как раз появился шанс разобраться лучше с Optional)

2022-12-13 15:26 UTC, akrecev commented on src/main/java/ru/yandex/practicum/filmorate/storage/db/GenreDBStorage.java
> +    public Genre get(int id) {
Да, все сервисы принимают Optional из хранилища и обрабатывают ошибки.

2022-12-13 17:05 UTC, akrecev commented on src/main/java/ru/yandex/practicum/filmorate/storage/db/FilmDbStorage.java
> +            throw new DataNotFoundException("id=" + id);
Да, перенес обработку исключений в сервис

2022-12-13 20:52 UTC, FanaticFiz approved these changes

2022-12-13 20:52 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmStorage.java
> +    Optional<Film> save(Film film);
Только find - поиск одиночного объекта должен быть с Optional.
А методам `save/update` он не нужен. Эти методы или выполнят свою работу или упадут с ексепшеном.

2022-12-13 20:52 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    public void validate(Film film) {
Если метод кидает ексепшн то его следует так и назвать `throwПоПричине`

А валидация, сама по себе, предусматривает возвращение какого то результата...

2022-12-13 20:52 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/storage/db/FilmDbStorage.java
> +    static Film filmMapper(ResultSet rs, int rowNum) throws SQLException {
Действительно!
Но это не отменяет того что он должен опуститься ниже публичных методов.
Общее правило расположения методов от самых видимых до приватных.

2022-12-13 20:52 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/storage/db/FilmDbStorage.java
> +        return Optional.ofNullable(films.isEmpty() ? null : films.get(0));
Есть хорошая практика делать отступ перед `return`.

Это выделяет точку выхода из метода визуально.
Есть только одно исключение: если метод начался сразу с return то отступ делать не нужно.

2022-12-13 21:01 UTC, akrecev commented on src/main/java/ru/yandex/practicum/filmorate/storage/db/FilmDbStorage.java
> +    static Film filmMapper(ResultSet rs, int rowNum) throws SQLException {
Понял, спасибо

2022-12-14 07:39 UTC, akrecev commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    public void validate(Film film) {
Переименовал метод

2022-12-14 07:40 UTC, akrecev commented on src/main/java/ru/yandex/practicum/filmorate/storage/db/FilmDbStorage.java
> +        return Optional.ofNullable(films.isEmpty() ? null : films.get(0));
Спасибо, не знал этого

2022-12-14 11:53 UTC, akrecev commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmStorage.java
> +    Optional<Film> save(Film film);
Так и сделал

2022-12-14 11:58 UTC, merged